### ISSUE TITLE
Update for newer devices

### ISSUE THREAD

**Issue by haythamodeh** [artyom-beilis/android_live_stacker#2]
Is it possible for an update to work on newer devices.

**Comment by artyom-beilis** [comment]
> Is it possible for an update to work on newer devices.

What do you mean newer devices? It works on Android 11 and 10 as I tested and should work.

What is the problem?

In any case I'm working on: https://github.com/artyom-beilis/OpenLiveStacker

Currently Linux only but next step is Android. And it works with both UVC and ASI ZWO cameras.
